### PR TITLE
[WIP] Adding ability to log in and cancel

### PR DESCRIPTION
**Pull request by jdax**
adding links in the home page to login to member account
adding link in the navigation to login to member account
adding links in membership#show to cancel the membership

### CODE REVIEW

**Comment by jdax** [comment]
still needs to add in tests and re-assess with login links

**Comment by indirect** [comment]
I think it will behave a bit better now, at least to the point where you can test it in local development. Sorry about that. 😬

I'm not very confident about my approach here of adding `cancelled_at` to memberships and using it to know if a member cancelled... the only part I am sure about is that after they have cancelled, the top of the membership page should say "your membership is cancelled". If you prefer to make that happen a different way, that seems totally reasonable. 👍🏻

**Comment by jdax** [comment]
A user should be able to login to their membership and cancel it from `/membership`
After canceling, the status of "cancelled" should be displayed to the user on the `/membership` page

**Comment by indirect** [comment]
closing in favor of #249, which contains all of these commits 👍

**Pull request closed without merging**
