### PR TITLE
Grant memberships a 3.5 day grace period on payments.

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by indirect** [comment]
👍

**Comment by parndt** [comment]
Oh hooray the tests fail due to some timing issue 😄

**Comment by parndt** [comment]
..or some database rounding issue

**Comment by parndt** [comment]
Fixed it thanks to a suggestion by @JonRowe to use `be_within`

**Comment by indirect** [comment]
Thanks!

**Pull request merged**
