### PR TITLE
Using latest releases of Ruby and Rails and added Foreman gem for dev…

### PR DESCRIPTION
**Pull request by heliocola**
Updated to latest RoR and added Foreman gem for development environment.
In the CONTRIBUTING.md, section "Configure Your Local Development Environment" suggests the use of 'foreman start'.

### CODE REVIEW

**Comment by indirect** [comment]
If you use foreman, it should be installed as part of the Heroku toolbelt, not as part of the application bundle. For reasons I never quite figured out, `bundle exec foreman` is broken in subtle was that `foreman` is not. :(

**Comment by heliocola** [comment]
@indirect I do have heroku toolbelt installed on my laptop but the foreman wasn't on my path or installed a stand alone binaries.
I only used foreman because of the directions in Contributing sections.
I can remove the foreman gem and update the Contributing to use only rails s, but in this case it won't run any of the workers.

**Comment by indirect** [comment]
@heliocola oh wow! Apparently Heroku just removed foreman and switched to `heroku local`: https://devcenter.heroku.com/changelog-items/692

**Comment by heliocola** [comment]
wow... what a timing!

**Pull request closed without merging**
