### PR TITLE
[wip] monthly update automation

### PR DESCRIPTION
**Pull request by indirect**
We have to write a monthly update every month, and a lot of the data in that monthly update could be fetched completely automatically. Let's start by grabbing information about GitHub projects automatically, and plan to (hopefully) eventually also grab and report on the financial information automatically.

### CODE REVIEW

**Comment by duckinator** [comment]
@indirect I just released how_is v18.1.0, which has the following API:

```ruby
require "how_is/contributions"

user, repo = "foo/bar".split("/")
start_date = "2017-07-01"
contributions = HowIs::Contributions.new(user: user, repo: repo, start_date: start_date)
contributions.summary("This month") #=> nearly identical to your git_summary() (argument is to change the part before the first comma, bc by default it returns a nicely-formatted date range)
contributions.new_contributors.map { |contributor| contributor["name"] } #=> list of new developers.
```
how_is itself doesn't actually use this yet, but it should work perfectly fine.

**Comment by duckinator** [comment]
WELL so much for that idea.

the script is currently broken, sorry @indirect.

it's after midnight, i'm gonna call it a day. i think i'm going to move how_is to something besides slop because that has _repeatedly_ been a problem.

**Comment by duckinator** [comment]
I released how_is v19.0.0 which removes the Slop conflict, but now it's conflicting on the Addressable gem.

I'll probably play dependency whack-a-mole tomorrow.

**Comment by duckinator** [comment]
As a note: The list of new contributors is available, but not used at the moment.

**Comment by duckinator** [comment]
@indirect i can't actually test this because i can't get it to run locally lmao

```
$ bundle exec ruby -v ./bin/create_update
<over 300 lines of output removed>
/home/ellen/dev/ruby/rubytogether/rubytogether.org/.bundle/gems/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant User (NameError)
$
```

**Comment by indirect** [comment]
@duckinator oh, yeah, that's true. If you've been added to the Heroku app, you can test it by running `heroku plugin:install run-localjs && bin/production run:local bin/create_update`. If you haven't been added, ping me and I'll do that.

**Comment by duckinator** [comment]
@indirect is this PR used in any capacity right now? It's old enough it still refers to inq as HowIs, so I'd be surprised. I'm properly winding down inq development, with the ultimate goal of archiving the repo. I can pull out the contributors-related stuff into its own significantly-smaller project, if that'd be useful for you.

**Comment by indirect** [comment]
nope, I haven't touched this for a long time. thanks for checking 👍🏻

**Pull request closed without merging**
